"""Add flexible access control: user_source_ips, server_groups, access_policies

Revision ID: 8419b886bc6d
Revises: 
Create Date: 2026-01-04 10:12:08.234796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8419b886bc6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_groups_id'), 'server_groups', ['id'], unique=False)
    op.create_index(op.f('ix_server_groups_name'), 'server_groups', ['name'], unique=True)
    op.create_table('server_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('server_id IS NOT NULL AND group_id IS NOT NULL', name='check_group_member_ids'),
    sa.ForeignKeyConstraint(['group_id'], ['server_groups.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_group_members_group_id'), 'server_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_server_group_members_id'), 'server_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_server_group_members_server_id'), 'server_group_members', ['server_id'], unique=False)
    op.create_table('user_source_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL', name='check_user_source_ip_user_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_source_ips_id'), 'user_source_ips', ['id'], unique=False)
    op.create_index(op.f('ix_user_source_ips_source_ip'), 'user_source_ips', ['source_ip'], unique=False)
    op.create_index(op.f('ix_user_source_ips_user_id'), 'user_source_ips', ['user_id'], unique=False)
    op.create_table('access_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_ip_id', sa.Integer(), nullable=True),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('target_group_id', sa.Integer(), nullable=True),
    sa.Column('target_server_id', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(scope_type = 'group' AND target_group_id IS NOT NULL AND target_server_id IS NULL) OR (scope_type IN ('server', 'service') AND target_server_id IS NOT NULL AND target_group_id IS NULL)", name='check_scope_targets'),
    sa.CheckConstraint("protocol IS NULL OR protocol IN ('ssh', 'rdp')", name='check_protocol_valid'),
    sa.CheckConstraint("scope_type IN ('group', 'server', 'service')", name='check_scope_type_valid'),
    sa.ForeignKeyConstraint(['source_ip_id'], ['user_source_ips.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['server_groups.id'], ),
    sa.ForeignKeyConstraint(['target_server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_policies_end_time'), 'access_policies', ['end_time'], unique=False)
    op.create_index(op.f('ix_access_policies_id'), 'access_policies', ['id'], unique=False)
    op.create_index(op.f('ix_access_policies_is_active'), 'access_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_access_policies_scope_type'), 'access_policies', ['scope_type'], unique=False)
    op.create_index(op.f('ix_access_policies_source_ip_id'), 'access_policies', ['source_ip_id'], unique=False)
    op.create_index(op.f('ix_access_policies_start_time'), 'access_policies', ['start_time'], unique=False)
    op.create_index(op.f('ix_access_policies_target_group_id'), 'access_policies', ['target_group_id'], unique=False)
    op.create_index(op.f('ix_access_policies_target_server_id'), 'access_policies', ['target_server_id'], unique=False)
    op.create_index(op.f('ix_access_policies_user_id'), 'access_policies', ['user_id'], unique=False)
    op.create_table('policy_ssh_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('allowed_login', sa.String(length=255), nullable=False),
    sa.CheckConstraint('policy_id IS NOT NULL', name='check_ssh_login_policy_id'),
    sa.ForeignKeyConstraint(['policy_id'], ['access_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_ssh_logins_id'), 'policy_ssh_logins', ['id'], unique=False)
    op.create_index(op.f('ix_policy_ssh_logins_policy_id'), 'policy_ssh_logins', ['policy_id'], unique=False)
    op.add_column('servers', sa.Column('ssh_port', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('rdp_port', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_source_ip'), 'users', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_source_ip'), table_name='users')
    op.drop_column('servers', 'rdp_port')
    op.drop_column('servers', 'ssh_port')
    op.drop_index(op.f('ix_policy_ssh_logins_policy_id'), table_name='policy_ssh_logins')
    op.drop_index(op.f('ix_policy_ssh_logins_id'), table_name='policy_ssh_logins')
    op.drop_table('policy_ssh_logins')
    op.drop_index(op.f('ix_access_policies_user_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_target_server_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_target_group_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_start_time'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_source_ip_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_scope_type'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_is_active'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_end_time'), table_name='access_policies')
    op.drop_table('access_policies')
    op.drop_index(op.f('ix_user_source_ips_user_id'), table_name='user_source_ips')
    op.drop_index(op.f('ix_user_source_ips_source_ip'), table_name='user_source_ips')
    op.drop_index(op.f('ix_user_source_ips_id'), table_name='user_source_ips')
    op.drop_table('user_source_ips')
    op.drop_index(op.f('ix_server_group_members_server_id'), table_name='server_group_members')
    op.drop_index(op.f('ix_server_group_members_id'), table_name='server_group_members')
    op.drop_index(op.f('ix_server_group_members_group_id'), table_name='server_group_members')
    op.drop_table('server_group_members')
    op.drop_index(op.f('ix_server_groups_name'), table_name='server_groups')
    op.drop_index(op.f('ix_server_groups_id'), table_name='server_groups')
    op.drop_table('server_groups')
    # ### end Alembic commands ###
